### ISSUE TITLE
rj fails to install on Ubuntu 14.04 (kernel 3.13)

### ISSUE THREAD

**Issue by ldesousa** [walware/rj-client#2]
I am trying to use StatET on Ubuntu 14.04, and rj is one of its requirements. When I try to install it I get the error message: "R is not configured with full Java support", even though "javareconf" is successful. I am using R 3.1.1 and OpenJDK 1.7, details go below. 

$ apt-cache policy r-base
r-base:
  Installed: 3.1.1-1trusty0
  Candidate: 3.1.1-1trusty0
  Version table:
 *** 3.1.1-1trusty0 0
        500 http://cran.rstudio.com/bin/linux/ubuntu/ trusty/ Packages
        100 /var/lib/dpkg/status
     3.1.0-1trusty0 0
        500 http://cran.rstudio.com/bin/linux/ubuntu/ trusty/ Packages
     3.0.2-1ubuntu1 0
        500 http://de.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages

$ java -version
java version "1.7.0_55"
OpenJDK Runtime Environment (IcedTea 2.4.7) (7u55-2.4.7-1ubuntu1)
OpenJDK 64-Bit Server VM (build 24.51-b03, mixed mode)

$ sudo su

#  R CMD javareconf
Java interpreter : /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
Java version     : 1.7.0_55
Java home path   : /usr/lib/jvm/java-7-openjdk-amd64
Java compiler    : /usr/bin/javac
Java headers gen.: /usr/bin/javah
Java archive tool: /usr/bin/jar

trying to compile and link a JNI progam
detected JNI cpp flags    :
detected JNI linker flags : -L$(JAVA_HOME)/jre/lib/amd64/server -ljvm
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2
-fstack-protector --param=ssp-buffer-size=4 -Wformat
-Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c conftest.c -o
conftest.o
gcc -std=gnu99 -shared -Wl,-Bsymbolic-functions -Wl,-z,relro -o
conftest.so conftest.o
-L/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server -ljvm
-L/usr/lib/R/lib -lR

JAVA_HOME        : /usr/lib/jvm/java-7-openjdk-amd64
Java library path: $(JAVA_HOME)/jre/lib/amd64/server
JNI cpp flags    :
JNI linker flags : -L$(JAVA_HOME)/jre/lib/amd64/server -ljvm
Updating Java configuration in /usr/lib/R
Done.

# R

R version 3.1.1 (2014-07-10) -- "Sock it to Me"
Copyright (C) 2014 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages(c("rj", "rj.gd"), repos="http://download.walware.de/rj-1.1")
Installing packages into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'http://download.walware.de/rj-1.1/src/contrib/rj_1.1.3-1.tar.gz'
Content type 'application/x-tar' length 333795 bytes (325 Kb)
opened URL
==================================================
downloaded 325 Kb

trying URL 'http://download.walware.de/rj-1.1/src/contrib/rj.gd_1.1.3-1.tar.gz'
Content type 'application/x-tar' length 119963 bytes (117 Kb)
opened URL
==================================================
downloaded 117 Kb

* installing *source* package ‘rj’ ...
checking R config... found
    R_HOME   : /usr/lib/R
checking for gcc... gcc -std=gnu99
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking Java support in R... configure: error: cannot determine
complete java config
    JAVA_HOME: /usr/lib/jvm/java-7-openjdk-amd64
    JAVA     : /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
    JAVAC    : /usr/bin/javac
    JAVAH    : /usr/bin/javah
    JAVA_CPPFLAGS:
    JAVA_LIBS: -L/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server -ljvm
    JAR      : /usr/bin/jar
R is not configured with full Java support. Please make sure
an JDK is installed and run
    R CMD javareconf
as root to add Java support to R.

If you don't have root privileges, run
    R CMD javareconf -e
to set all Java-related variables and then install the package.
ERROR: configuration failed for package ‘rj’
* removing ‘/usr/local/lib/R/site-library/rj’
ERROR: dependency ‘rj’ is not available for package ‘rj.gd’
* removing ‘/usr/local/lib/R/site-library/rj.gd’

The downloaded source packages are in
    ‘/tmp/RtmpjtztJ5/downloaded_packages’
Warning messages:
1: In install.packages(c("rj", "rj.gd"), repos =
"http://download.walware.de/rj-1.1") :
  installation of package ‘rj’ had non-zero exit status
2: In install.packages(c("rj", "rj.gd"), repos =
"http://download.walware.de/rj-1.1") :
  installation of package ‘rj.gd’ had non-zero exit status
>

**Comment by wahlbrink** [comment]
Not part of rj-client.
